<a href="https://colab.research.google.com/github/Pranavlovescode/Mumbai-Price-predictor/blob/master/mumbai_price_predictor_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Mumbai Price Detector ML model**

In [71]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [72]:
df = pd.read_csv('Mumbai1.csv')
df.head()

Unnamed: 0    Price  Area  Location  No. of Bedrooms  New/Resale  \
0           0  4850000   720  Kharghar                1           0   
1           1  4500000   600  Kharghar                1           0   
2           2  6700000   650  Kharghar                1           0   
3           3  4500000   650  Kharghar                1           0   
4           4  5000000   665  Kharghar                1           0   

   Gymnasium  Lift Available  Car Parking  Maintenance Staff  24x7 Security  \
0          0               1            1                  1              1   
1          1               1            1                  1              1   
2          1               1            1                  1              1   
3          0               1            1                  1              1   
4          0               1            1                  1              1   

   Children's Play Area  Clubhouse  Intercom  Landscaped Gardens  \
0                     0          0         0                   0   
1                     0          1         0                   0   
2                     1          1         1                   0   
3                     0          0         1                   1   
4                     0          0         1                   1   

   Indoor Games  Gas Connection  Jogging Track  Swimming Pool  
0             0               0              0              0  
1             0               0              1              1  
2             0               0              1              1  
3             0               0              0              0  
4             0               0              0              0

## **Exploratory Data Analysis**

In [ ]:
df.isnull().sum()

Unnamed: 0              0
Price                   0
Area                    0
Location                0
No. of Bedrooms         0
New/Resale              0
Gymnasium               0
Lift Available          0
Car Parking             0
Maintenance Staff       0
24x7 Security           0
Children's Play Area    0
Clubhouse               0
Intercom                0
Landscaped Gardens      0
Indoor Games            0
Gas Connection          0
Jogging Track           0
Swimming Pool           0
dtype: int64

In [ ]:
print(df['Location'].value_counts())
print(df.shape)

Location
Kharghar             533
Thane West           418
Mira Road East       390
Ulwe                 319
Borivali West        176
                    ... 
worli sea face         1
Sea Face               1
Shiv Sagar Estate      1
Natakwala Lane         1
Padle Gaon             1
Name: count, Length: 413, dtype: int64
(6347, 19)


In [76]:
filtered_counts = df['Location'].value_counts()[df['Location'].value_counts() < 50]
print(filtered_counts)
filtered_counts = df['Location'].value_counts()[df['Location'].value_counts() > 50]
print(filtered_counts)

Location
Dombivali            44
Seawoods             44
Borivali East        43
Vasai                41
Badlapur East        40
                     ..
worli sea face        1
Sea Face              1
Shiv Sagar Estate     1
Natakwala Lane        1
Padle Gaon            1
Name: count, Length: 387, dtype: int64
Location
Kharghar            533
Thane West          418
Mira Road East      390
Ulwe                319
Borivali West       176
Kalyan West         176
Nala Sopara         172
Malad West          163
Andheri West        161
Powai               141
Kandivali East      141
Panvel              136
Chembur             135
Kandivali West      115
Virar               107
Kamothe             104
Goregaon West        86
Malad East           85
Andheri East         83
Mulund West          76
Taloja               65
Goregaon East        64
Ville Parle East     63
Boisar               61
Dahisar              58
Naigaon East         55
Name: count, dtype: int64


In [77]:
df['Location'] = df['Location'].apply(lambda x: 'Other' if df['Location'].value_counts()[x] <= 50 else x)
df

Unnamed: 0     Price  Area    Location  No. of Bedrooms  New/Resale  \
0              0   4850000   720    Kharghar                1           0   
1              1   4500000   600    Kharghar                1           0   
2              2   6700000   650    Kharghar                1           0   
3              3   4500000   650    Kharghar                1           0   
4              4   5000000   665    Kharghar                1           0   
...          ...       ...   ...         ...              ...         ...   
6342        6342   2485000   700       Other                1           1   
6343        6343  14500000   900  Thane West                2           0   
6344        6344  14500000   900  Thane West                2           0   
6345        6345   4100000  1380      Boisar                3           0   
6346        6346   2750000   700       Other                1           1   

      Gymnasium  Lift Available  Car Parking  Maintenance Staff  \
0             0               1            1                  1   
1             1               1            1                  1   
2             1               1            1                  1   
3             0               1            1                  1   
4             0               1            1                  1   
...         ...             ...          ...                ...   
6342          0               0            0                  0   
6343          0               0            0                  0   
6344          0               1            0                  0   
6345          0               0            0                  0   
6346          1               1            1                  0   

      24x7 Security  Children's Play Area  Clubhouse  Intercom  \
0                 1                     0          0         0   
1                 1                     0          1         0   
2                 1                     1          1         1   
3                 1                     0          0         1   
4                 1                     0          0         1   
...             ...                   ...        ...       ...   
6342              0                     0          0         0   
6343              0                     0          0         0   
6344              0                     0          0         1   
6345              0                     0          0         0   
6346              1                     1          1         0   

      Landscaped Gardens  Indoor Games  Gas Connection  Jogging Track  \
0                      0             0               0              0   
1                      0             0               0              1   
2                      0             0               0              1   
3                      1             0               0              0   
4                      1             0               0              0   
...                  ...           ...             ...            ...   
6342                   0             0               0              0   
6343                   0             0               0              0   
6344                   0             0               1              0   
6345                   0             0               0              0   
6346                   1             1               0              1   

      Swimming Pool  
0                 0  
1                 1  
2                 1  
3                 0  
4                 0  
...             ...  
6342              0  
6343              0  
6344              0  
6345              0  
6346              1  

[6347 rows x 19 columns]

In [78]:
df2 = df.drop(['Unnamed: 0'],axis=1)
print(df2.shape)

(6347, 18)


**One Hot Encoding to convert categorical data into numbers**

In [79]:
from sklearn.model_selection import train_test_split
X = df2.iloc[:,1:18]
y =df2.iloc[:,0:1]
print(X)
print(y)

      Area    Location  No. of Bedrooms  New/Resale  Gymnasium  \
0      720    Kharghar                1           0          0   
1      600    Kharghar                1           0          1   
2      650    Kharghar                1           0          1   
3      650    Kharghar                1           0          0   
4      665    Kharghar                1           0          0   
...    ...         ...              ...         ...        ...   
6342   700       Other                1           1          0   
6343   900  Thane West                2           0          0   
6344   900  Thane West                2           0          0   
6345  1380      Boisar                3           0          0   
6346   700       Other                1           1          1   

      Lift Available  Car Parking  Maintenance Staff  24x7 Security  \
0                  1            1                  1              1   
1                  1            1                  1             

In [154]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [81]:
y_train

Price
4670   2300000
3953   6000000
1972  65000000
2170   7600000
5486   6542000
...        ...
979    6656000
6121  18000000
5828   6500000
543    8500000
5304   2900000

[5077 rows x 1 columns]

In [116]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first',sparse_output=False)

In [91]:
X_train_new = ohe.fit_transform(X_train[['Location']])
X_train_new
# X_train_new.shape

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [92]:
X_test_new = ohe.fit_transform(X_test[['Location']])
X_test_new
# X_test_new.shape

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [93]:
X_train_final = np.concatenate((X_train_new,X_train),axis=1)
X_train_final

array([[0.0, 0.0, 0.0, ..., 0, 0, 0],
       [0.0, 0.0, 0.0, ..., 0, 0, 1],
       [0.0, 0.0, 0.0, ..., 0, 0, 0],
       ...,
       [0.0, 0.0, 0.0, ..., 0, 1, 1],
       [0.0, 0.0, 0.0, ..., 0, 0, 0],
       [0.0, 0.0, 0.0, ..., 1, 0, 0]], dtype=object)

In [94]:
X_test_final = np.concatenate((X_test_new,X_test),axis=1)
X_test_final

array([[0.0, 0.0, 0.0, ..., 0, 1, 1],
       [0.0, 0.0, 0.0, ..., 0, 0, 0],
       [0.0, 0.0, 0.0, ..., 0, 1, 1],
       ...,
       [0.0, 0.0, 0.0, ..., 0, 1, 1],
       [0.0, 0.0, 0.0, ..., 1, 1, 1],
       [0.0, 0.0, 0.0, ..., 1, 1, 1]], dtype=object)

**Training the model**

In [139]:
from sklearn.compose import ColumnTransformer
transformer = ColumnTransformer(transformers=[
    ('tnf1',OneHotEncoder(sparse_output=False,drop='first'),['Location'])
],remainder='passthrough')


In [140]:
X_train_transformed = transformer.fit_transform(X_train)

In [141]:
X_test_transformed=transformer.fit_transform(X_test)

**Predicting using Linear Regression**

In [155]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train_transformed,y_train)

LinearRegression()

In [157]:
lr.score(X_test_transformed,y_test)

-0.028370714805979302

In [144]:
lr.predict(X_test_transformed)

array([[21045950.65509453],
       [16445595.42036969],
       [36444757.63544554],
       ...,
       [37590053.91132811],
       [24694016.12799576],
       [ 4971297.9459194 ]])

In [145]:
y_test

Price
6089  24000000
4925   8733000
3234  24000000
3263   5500000
199    4760000
...        ...
1104  16000000
2045   8500000
2175  52500000
5575  18000000
3127  10000000

[1270 rows x 1 columns]

**Predicting the model using SVM**

In [158]:
from sklearn.svm import SVC
svm = SVC()
svm.fit(X_train_transformed,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

In [159]:
svm.score(X_test_transformed,y_test)

0.02204724409448819

**Predicting using Random Forest**

In [160]:
from sklearn.ensemble import RandomForestClassifier
r = RandomForestClassifier()
r.fit(X_train_transformed,y_train)

<ipython-input-160-122bfecba15c>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  r.fit(X_train_transformed,y_train)


RandomForestClassifier()

In [161]:
r.score(X_test_transformed,y_test)

0.006299212598425197

In [162]:
from sklearn.linear_model import LogisticRegression
logr = LogisticRegression()
logr.fit(X_train_transformed,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [163]:
logr.score(X_test_transformed,y_test)

0.02283464566929134